### ISSUE TITLE
Attributing a url for individual queries in Bioquery

### ISSUE THREAD

**Issue by oolonek** [biosoda/bioquery#12]
It would be of interest (e.g. to share a given query with a collaborator) to have a URL pointing to each query at http://biosoda.expasy.org/build_biosodafrontend/

**Comment by dssib** [comment]
added in https://github.com/biosoda/bioquery/commit/fc8563e843af0c909dc1b82fbd46b420ac704fc6.

You can now use the parameter ?search to look for a specific text, this can be the embedded ID of the query:

https://biosoda.expasy.org/bioquery-dbgi/?search=Q1

Or any kind of text from the question itself, e.g. "Among the structural annotations from Tabernaemontana coffeoides (Apocynaceae) seeds extract, which ones contain an aspidospermidine substructure?"

https://biosoda.expasy.org/bioquery-dbgi/?search=Among%20the%20structural%20annotations%20from%20Tabernaemontana%20coffeoides%20(Apocynaceae)%20seeds%20extract,%20which%20ones%20contain%20an%20aspidospermidine%20substructure?
